version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
